version: '2'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  weather-service:
    build:
      context: ./weather-service
      dockerfile: Dockerfile
    ports:
      - 8081:8080