services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    ports:
      - 8080:8080
  weather-service:
    build:
      context: ./weather-service
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - USER_SERVICE_HOST=http://user-service:8080
      - RABBIT_HOST=amqp://guest:guest@rabbitmq:5672/
      - NOTIFICATION_QUEUE=notifications
    ports:
      - 8081:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - USER_SERVICE_HOST=http://user-service:8080
      - WEB_NOTIFICATION_API_HOST=http://web-notification-api-mock:8080
      - RABBIT_HOST=amqp://guest:guest@rabbitmq:5672/
      - NOTIFICATION_QUEUE=notifications
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
  web-notification-api-mock:
    build:
      context: ./web-notification-api-mock
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    ports:
      - 8083:8080
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 5